In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.patheffects as pe
import seaborn as sns
import os

In [2]:
df= pd.read_csv('Village_profile_UBA_(Responses)-Form_Responses_1_Copy.csv')

In [3]:
df.head()

,Timestamp,Survey type,Village Name,Household ID (House No.),Name of Head of Household,Gender,Contact Number of Household,Social Category,Total Family Members,Main Occupation,...,Livelihood Schemes [PM Fasal Bima],Livelihood Schemes [Pension Schemes],Awareness about Gram Sabha meetings,Participation in village development,Major village issues,Most urgent need of the village,Suggestions for village development,Enumerator Name,UID,Date
0,01-12-2026 13:22,Baseline,Bajhedi,NaN,Mohan Singh,Male,9914104719,General,4,Service,...,Aware,Aware,No,Occasional,"Water, Education, Employment",Road improvements,Making of roads,Hitanshi,25bbl70047,01-12-2026
1,1/13/2026 12:48:58,Baseline,Baroli,144,Harshant veer,Male,NaN,Scheduled Tribe,4,Service,...,Aware,Aware,Yes,Occasional,"Water, Environment",Drainage system,Drainage system,Yashmi and Aditi,25bcs12827 and 25bcs10021,1/13/2026
2,01-12-2026 11:48,Baseline,Bhago Majra,NaN,Jaswinder kour,Female,9781068967,General,6,Agriculture,...,Not Aware,Not Aware,No,Never,Health,Healthcare,Cleaning of waste,Bhagyashree,24btt10013,01-12-2026
3,01-12-2026 13:48,Baseline,Bajhedi,NaN,Gurinder kaur,Female,8872445393,General,4,Business,...,Not Aware,Not Aware,Yes,Never,"Water, Health, Environment","Transport, Dispensary and pond purification",Regular transport and dispensary,Pushp Ankit kotwal,25bbl70011,01-12-2026
4,1/13/2026 11:19:16,Baseline,Bhago Majra,NaN,Kulwant Singh,Male,7696486215,General,5,Agriculture,...,Aware,Aware,Yes,Occasional,Environment,"All good there is gym in village,school ,every...",No,Kushagra Sharma,25BBE10175,1/13/2026

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 855 entries, 0 to 854
Data columns (total 75 columns):
 #   Column                                                   Non-Null Count  Dtype
---  ------                                                   --------------  -----
 0   Timestamp                                                855 non-null    object
 1   Survey type                                              855 non-null    object
 2     Village Name                                           855 non-null    object
 3     Household ID (House No.)                               357 non-null    object
 4     Name of Head of Household                              854 non-null    object
 5     Gender                                                 855 non-null    object
 6   Contact Number of Household                              491 non-null    object
 7     Social Category                                        855 non-null    object
 8     Total Family Members                                   855 non-null    object
 9     Main Occupation                                        855 non-null    object
 10    Approx. Annual Household Income                        855 non-null    object
 11    Distance to nearest health facility                    855 non-null    object
 12    Type of facility used                                  855 non-null    object
 13    ASHA/ANM visit                                         855 non-null    object
 14    Immunization status of children (0-5)                  855 non-null    object
 15    Pregnant women received ANC services                   646 non-null    object
 16    Last delivery was institutional  (in any hospital)     855 non-null    object
 17    Nutritional issues  of children                        71 non-null     object
 18    Common diseases                                        420 non-null    object
 19    Toilet availability                                    855 non-null    object
 20    Handwashing with soap                                  855 non-null    object
 21    Health Schemes   [Ayushman Bharat (PM-JAY)]            855 non-null    object
 22    Health Schemes   [Janani Suraksha Yojana]              855 non-null    object
 23    Health Schemes   [Janani Shishu Suraksha Karyakram]    855 non-null    object
 24    Health Schemes   [Poshan Abhiyaan / ICDS]              855 non-null    object
 25    Literacy status of household                           855 non-null    object
 26    Children enrolled in school                            855 non-null    object
 27    Type of school                                         733 non-null    object
 28    Distance to nearest school                             855 non-null    object
 29    School dropout cases  in the household                 855 non-null    object
 30    Reason for dropout                                     336 non-null    object
 31    Access to digital devices                              805 non-null    object
 32    Girls continuing education beyond Class X              855 non-null    object
 33    Need for remedial/coaching support                     855 non-null    object
 34    Education Schemes   [PM POSHAN]                        855 non-null    object
 35    Education Schemes   [Pre/Post Matric Scholarship]      855 non-null    object
 36    Education Schemes   [National Merit Scholarship]       855 non-null    object
 37    Source of drinking water                               855 non-null    object
 38    Availability  of water supply                          855 non-null    object
 39    Quality of drinking water                              855 non-null    object
 40    Household water treatment  through purifier            855 non-null    object
 41    Solid waste disposal method                            855 non-null    object
 42    Drainage system                                        813 non-null    object
 43    Open defecation in village                             855 non-null    object
 44    Presence of pond/water body                            855 non-null    object
 45    Condition of pond                                      855 non-null    object
 46    Usage of pond                                          855 non-null    object
 47    Major environmental problems                           855 non-null    object
 48    Renewable energy usage                                 277 non-null    object
 49    Disaster vulnerability                                 333 non-null    object
 50    Willingness to participate                             855 non-null    object
 51   Household women  engaged in income activity             855 non-null    object
 52    Type of activity                                       855 non-null    object
 53    SHG membership                                         855 non-null    object
 54    Bank account in woman’s name                           855 non-null    object
 55    Role of women in decision-making                       855 non-null    object
 56    Women Schemes   [Pradhan Mantri Matru Vandana Yojana]  855 non-null    object
 57    Women Schemes   [NRLM]                                 855 non-null    object
 58    Women Schemes   [Beti Bachao Beti Padhao]              855 non-null    object
 59    Women Schemes   [Sukanya Samriddhi]                    855 non-null    object
 60    Skill-trained member in household                      855 non-null    object
 61    Skills required                                        855 non-null    object
 62    Migration for employment                               362 non-null    object
 63    Livelihood Schemes   [MGNREGA]                         855 non-null    object
 64    Livelihood Schemes   [PM-KISAN]                        855 non-null    object
 65    Livelihood Schemes   [PM Fasal Bima]                   855 non-null    object
 66    Livelihood Schemes   [Pension Schemes]                 855 non-null    object
 67    Awareness about Gram Sabha meetings                    855 non-null    object
 68    Participation in village development                   855 non-null    object
 69    Major village issues                                   855 non-null    object
 70    Most urgent need of the village                        828 non-null    object
 71    Suggestions for village development                    833 non-null    object
 72    Enumerator Name                                        855 non-null    object
 73  UID                                                      854 non-null    object
 74    Date                                                   855 non-null    object
dtypes: object(75)
memory usage: 501.1+ KB

In [5]:
df.describe()

,Timestamp,Survey type,Village Name,Household ID (House No.),Name of Head of Household,Gender,Contact Number of Household,Social Category,Total Family Members,Main Occupation,...,Livelihood Schemes [PM Fasal Bima],Livelihood Schemes [Pension Schemes],Awareness about Gram Sabha meetings,Participation in village development,Major village issues,Most urgent need of the village,Suggestions for village development,Enumerator Name,UID,Date
count,855,855,855,357,854,855,491,855,855,855,...,855,855,855,855,855,828,833,855,854,855
unique,791,2,39,225,727,2,471,4,22,13,...,4,4,2,3,31,547,612,400,375,23
top,01-12-2026 11:59,Baseline,Baroli,Na,Gurpreet Singh,Male,9878775908,General,5,Agriculture,...,Not Aware,Aware,Yes,Occasional,Water,Hospital,Education,Raghav mandira,25BFT10043,1/15/2026
freq,6,846,91,7,6,688,3,483,214,314,...,426,410,581,375,97,28,14,9,9,165

# Data Preprocessing

In [6]:
print("Dataset Shape:", df.shape)

Dataset Shape: (855, 75)

In [7]:
df.columns = df.columns.str.strip()

In [8]:
df['Total Family Members'] = pd.to_numeric(df['Total Family Members'], errors='coerce')

In [9]:
df['Village Name'] = df['Village Name'].str.strip().str.lower().str.replace(r'\s+', ' ', regex=True)
df['Village Name'].unique()

array(['bajhedi', 'baroli', 'bhago majra', 'charanjit singh', 'deh kalan',
       'garangan', 'hassanpur', 'jarnal singh', 'kalewal', 'madan heri',
       'nabipur', 'rasid mahomad', 'rora', 'sahauran', 'sukhwinder',
       'village', 'sill', 'fatehpur theri', 'machipur'], dtype=object)

In [10]:
df['Village Name'] = df['Village Name'].str.title()
df['Village Name'].value_counts()

Village Name
Baroli             93
Sill               90
Rora               89
Sahauran           89
Bajhedi            84
Bhago Majra        79
Fatehpur Theri     74
Garangan           72
Kalewal            44
Deh Kalan          38
Hassanpur          36
Madan Heri         34
Nabipur            21
Jarnal Singh        5
Machipur            3
Rasid Mahomad       1
Sukhwinder          1
Village             1
Charanjit Singh     1
Name: count, dtype: int64

In [11]:
invalid_entries = ['Jarnal Singh', 'Rasid Mahomad','Sukhwinder', 'Charanjit Singh','Village']
df = df[~df['Village Name'].isin(invalid_entries)]

In [12]:
df['Village Name'].value_counts()

Village Name
Baroli            93
Sill              90
Rora              89
Sahauran          89
Bajhedi           84
Bhago Majra       79
Fatehpur Theri    74
Garangan          72
Kalewal           44
Deh Kalan         38
Hassanpur         36
Madan Heri        34
Nabipur           21
Machipur           3
Name: count, dtype: int64

folder_path = "Village_Wise_Data"
os.makedirs(folder_path, exist_ok=True)

for village, data in df_all_villages.groupby('Village Name'):
    file_name = f"{folder_path}/{village.replace(' ', '_')}.csv"
    data.to_csv(file_name, index=False)

print("All village files saved successfully!")